### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by ychuest** [Somewhat120/LLM_DDA#1]
Where is "generate_emb.py" located in the project? Can you provide the full code, yangchengyjs@163.com

**Comment by gu-yaowen** [comment]
thank you for the interest on our project. The core LLM embedding generation code will be released after the manuscript is accepted.

**Comment by ychuest** [comment]
I look forward to your manuscript being accepted by the journal. I hope that after the paper is accepted, you can release the complete code of the project, which will benefit many more researchers.
