### ISSUE TITLE
Is there an advance version of this article available, please?

### ISSUE THREAD

**Issue by ychuest** [Somewhat120/LLM_DDA#2]

**Comment by gu-yaowen** [comment]
Hi, thanks for the continuous interest on our work. Fortunately, the study got accepted and is about to be published soon. We have submitted lasting part of codes, including zero-shot templates, description generation, and LLM embedding generation, as well as standard performance results of our method. Please feel free to find them following the guidance of README file, and also please kindly considering citing our work after the article is accessible.

**Comment by ychuest** [comment]
I am glad that your team's paper was accepted by the journal. I look forward to downloading your article and reading it at the first opportunity.









--

| |
湖南科技大学计算机学院杨城
|
|
***@***.***
|



在 2024-07-29 07:47:50，"Yaowen Gu" ***@***.***> 写道：

Hi, thanks for the continuous interest on our work. Fortunately, the study got accepted and is about to be published soon. We have submitted lasting part of codes, including zero-shot templates, description generation, and LLM embedding generation, as well as standard performance results of our method. Please feel free to find them following the guidance of README file, and also please kindly considering citing our work after the article is accessible.
